[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]

[build]
jobs = 1

[target.x86_64-pc-windows-msvc]
rustflags = ["--cfg=web_sys_unstable_apis", "-Zlocation-detail=none", "-Ctarget-cpu=native", "-Zunstable-options"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg=web_sys_unstable_apis", "-Zlocation-detail=none", "-Ctarget-cpu=native", "-Zunstable-options"]
